POST http://localhost:8000/api/register
Content-Type: application/json

{"password": "password", "email": "user2@example.com"}

### 

POST http://localhost:8000/api/login
Content-Type: application/json

{"email": "user@example.com", "password": "password"}

###

POST http://localhost:8000/api/refresh
Content-Type: application/json

{"refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MTMyODE5MjEsImlhdCI6MTcxMzI4MTkwNn0.W4Jn_AKMVxTDVCZOCK9oMichOM95R_4kempBx5k49Ug"}

###

POST http://localhost:8000/api/logout
Content-Type: application/json

{"refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MTU3ODc4ODIsImlhdCI6MTcxMzE5NTg4Mn0.LuiSOl05s_Beq7t1osHrv34idt8yyH8bJr0budRiMPc"}

###

GET http://localhost:8000/api/me
Header: Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3MTMyODE3NjksImlhdCI6MTcxMzI4MTczOX0.G9IMdcoA_PQ75vVMEWPHBrcuud5-t8iFpNPrCYvsr84
Content-Type: application/json

###

PUT http://localhost:8000/api/me
Header: Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3MTMyODE3NjksImlhdCI6MTcxMzI4MTczOX0.G9IMdcoA_PQ75vVMEWPHBrcuud5-t8iFpNPrCYvsr84
Content-Type: application/json

{"username": "John Smith"}