# Generated by Django 5.0.4 on 2024-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
