# Generated by Django 5.0.4 on 2024-04-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="token",
            new_name="refresh_token",
        ),
    ]
