# Generated by Django 5.0.4 on 2024-04-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_token_user_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="refresh_token",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
